### ISSUE TITLE
Land model Post-Processing Work Flow (each step is 1 separate script/function)

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#261]

**Comment by rburghol** [comment]
@jdkleiner see above - I tried to lay out the script names and arguments that each of 2 post-processing component scripts should have here. I'd like to get your thoughts about this as a development strategy going forward.

**Comment by glenncampagna** [comment]
First version of working export script can be found here: https://github.com/HARPgroup/HARParchive/blob/master/HARP-2022-Summer/export_hsp_h5.R
 
- Everything is accomplished within the ../land/hsp2_2022/eos folder right now since that is the location of our h5 files

**Comment by jdkleiner** [comment]
@rburghol I think what you've laid out here is sensible. Separating the h5->CSV and CSV->summary stats portions of the process into separate scripts makes the most sense. The analysts should be able to take what they learned this morning (posting model stats as properties) the next step in ta hsp_pwater.R script

**Comment by glenncampagna** [comment]
### Running the Scripts
- The export script is run in the terminal/git bash window by first navigating to the directory with the needed h5s (/media/model/p6/out/land/hsp2_2022/eos/), and running the script and using the command:
**Rscript [export_hsp_h5.R] [h5_file_path] [output_file_path] [data_source_table]**
  where:
  [h5_file_path] = the name of the h5 file data is being retrieved from (forA51800.R)
  [output_file_path] = name of csv being saved to directory 
  (for example pwater_test.csv)
  [data_source_table] = path to table in h5 (/RESULTS/
	PERLND_001/PWATER/table)

- The summary script is also run in the terminal/git bash window by navigating to 
		directory above and using the command:
**Rscript hsp_pwater.R [land_segment_name] [scenario_name] [pwater_file_path]**
where:
		[land_segment_name] = name of land segment (A51800)
		[scenario_name] = (p532sova_2021)
[pwater_file_path] = name of csv file created using export script

**Comment by juliabruneau** [comment]
**Update:**

1. We changed the image property settings to: http://deq1.bse.vt.edu:81/p532/out/land/p532sova_2021/forA51800.fig.totalOut.png 
    * Where the file path is /p532/out/land/p532sova_2021
    * The filenames were edited to be shorter: _forA51800.fig.AGWS.png_ and _forA51800.fig.totalOut.png_ 

We have pushed these updated files (exports and images) into VAHydro to verify that they work. If @rburghol or @jdkleiner could remove all the files from the scenario, we can run the script again to just have the correct files remaining (there are a lot of duplicates now). 

2. We were able to attach a command into the first script to remove the original h5 file after creating the csv file out of it

We are looking into running the script with the full path now.

**Comment by glenncampagna** [comment]
### Error when running hsp_pwater.R with full path 
When attempting to run the summary script from our home directory and using a full path, with a directory and file name, we've gotten an error:
```
$ Rscript hsp_pwater.R A51800 p532sova_2021 /media/model/p6/out/land/hsp2_2022/eos/pwater_test.csv 'for'
Fatal error: cannot create 'R_TempDir'
```

 We are working on fixing this and adding an output_file_path command argument to the hsp_pwater.R script

**Comment by gcambridge** [comment]
### Image generation batch script for all land segments in a basin. 

I started working on the batch script to generate plots for all land segments in a basin, and had a few questions about the arguements.

I was able to simplify all the arguments used in the two R scripts down to three components (Land use, Land segment name, and scenario name). 

![image](https://user-images.githubusercontent.com/19675203/178819089-b20355af-3af0-4c7c-8c95-2e903e8806b7.png)

However I was unclear on a couple things: 
1. How to source the land use for each land segment
2. Can I hard-code the data_source_table in? (i.e /RESULTS/PERLND_P001/PWATER/table)
3. Should the building of the different arguments for the R scripts happen in the Batch Script?

**Comment by gcambridge** [comment]
@rburghol @jdkleiner we are testing the batch script and are running into the following permission denied errors when attempting to create the export directories: 

`mkdir: cannot create directory ‘/media/model/p532/out/land/hsp2_2022/eos’: Permission denied`
`mkdir: cannot create directory ‘/media/model/p532/out/land/hsp2_2022/images’: Permission denied`

Is there a way for you all to give us permissions to create and add files to these directories, or should we try exporting somewhere else for now?

**Comment by glenncampagna** [comment]
### Data harvesting batch script created and tested for OR1_7700_7980
https://github.com/HARPgroup/HARParchive/blob/master/HARP-2022-Summer/batch_harvest.bat
This batch script takes arguments for scenario and river segment and exports all pwater and iwater data tables to the same directory
Test: 
`/opt/model/p53/p532c-sova$  bash ~/batch_harvest.bat hsp2_2022 OR1_7700_7980`
Output: 
```
/media/model/p532/out/land/hsp2_2022/pwater$ ls
afoA51011_iwater.csv  cfoA51011_iwater.csv  homA51011_pwater.csv  hywA51011_pwater.csv  nhiA51011_pwater.csv  nloA51011_pwater.csv  rcnA51011_pwater.csv  trpA51011_pwater.csv
afoA51037_iwater.csv  cfoA51037_iwater.csv  homA51037_pwater.csv  hywA51037_pwater.csv  nhiA51037_pwater.csv  nloA51037_pwater.csv  rcnA51037_pwater.csv  trpA51037_pwater.csv
alfA51011_pwater.csv  cidA51011_iwater.csv  hvfA51011_pwater.csv  lwmA51011_pwater.csv  nhoA51011_pwater.csv  npaA51011_pwater.csv  rexA51011_pwater.csv  ursA51011_pwater.csv
alfA51037_pwater.csv  cidA51037_iwater.csv  hvfA51037_pwater.csv  lwmA51037_pwater.csv  nhoA51037_pwater.csv  npaA51037_pwater.csv  rexA51037_pwater.csv  ursA51037_pwater.csv
ccnA51011_pwater.csv  cpdA51011_pwater.csv  hwmA51011_pwater.csv  nalA51011_pwater.csv  nhyA51011_pwater.csv  npdA51011_pwater.csv  ridA51011_iwater.csv
ccnA51037_pwater.csv  cpdA51037_pwater.csv  hwmA51037_pwater.csv  nalA51037_pwater.csv  nhyA51037_pwater.csv  npdA51037_pwater.csv  ridA51037_iwater.csv
cexA51011_pwater.csv  forA51011_pwater.csv  hyoA51011_pwater.csv  nexA51011_pwater.csv  nidA51011_iwater.csv  pasA51011_pwater.csv  rpdA51011_pwater.csv
cexA51037_pwater.csv  forA51037_pwater.csv  hyoA51037_pwater.csv  nexA51037_pwater.csv  nidA51037_iwater.csv  pasA51037_pwater.csv  rpdA51037_pwater.csv
```
It is confirmed that all 'iwater' tables came from land uses classified as impervious by this model version, and both the pwater and water csvs were populated with the target data

**Comment by juliabruneau** [comment]
When trying to run the hsp2 model for the basin: OR4_8120_7890, me and @glenncampagna received errors.
The directory used: `/opt/model/p53/p532c-sova/`
Command used: `HSP_VERSION=hsp2;export HSP_VERSION;cbp run_land.csh hsp2_2022 OR4_8120_7890`

My error: 
```
Unable to open/create file 'rcnA51770.h5'
Traceback (most recent call last):
  File "/usr/local/bin/hsp2", line 11, in <module>
    load_entry_point('HSPsquared', 'console_scripts', 'hsp2')()
  File "/opt/model/HSPsquared/HSP2tools/HSP2_CLI.py", line 60, in main
    mando.main()
  File "/usr/local/lib/python3.8/dist-packages/mando/core.py", line 208, in __call__
    return self.execute(sys.argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/mando/core.py", line 204, in execute
    return command(*a)
  File "/opt/model/HSPsquared/HSP2tools/HSP2_CLI.py", line 24, in run
    hdf5_instance = HDF5(hdfname)
  File "/opt/model/HSPsquared/HSP2IO/hdf.py", line 13, in __init__
    self._store = pd.HDFStore(file_path)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/pytables.py", line 561, in __init__
    self.open(mode=mode, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/pytables.py", line 710, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tables/file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tables/file.py", line 778, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1400, in H5F__open
    unable to open file
  File "H5Fint.c", line 1817, in H5F_open
    problems closing file
  File "H5Fint.c", line 1279, in H5F__dest
    problems closing file
  File "H5Faccum.c", line 1070, in H5F__accum_reset
    can't flush metadata accumulator
  File "H5Faccum.c", line 1033, in H5F__accum_flush
    file write failed
  File "H5FDint.c", line 258, in H5FD_write
    driver write request failed
  File "H5FDsec2.c", line 811, in H5FD_sec2_write
    file write failed: time = Wed Jul 27 13:23:47 2022
, filename = 'rcnA51770.h5', file descriptor = 3, errno = 28, error message = 'No space left on device', buf = 0x3688118, total write size = 800, bytes this sub-write = 800, bytes actually written = 18446744073709551615, offset = 0
  File "H5Fint.c", line 1783, in H5F_open
    unable to flush superblock
  File "H5Fio.c", line 198, in H5F_flush_tagged_metadata
    can't reset accumulator
  File "H5Faccum.c", line 1070, in H5F__accum_reset
    can't flush metadata accumulator
  File "H5Faccum.c", line 1033, in H5F__accum_flush
    file write failed
  File "H5FDint.c", line 258, in H5FD_write
    driver write request failed
  File "H5FDsec2.c", line 811, in H5FD_sec2_write
    file write failed: time = Wed Jul 27 13:23:47 2022
, filename = 'rcnA51770.h5', file descriptor = 3, errno = 28, error message = 'No space left on device', buf = 0x377bd38, total write size = 96, bytes this sub-write = 96, bytes actually written = 18446744073709551615, offset = 0
```
This is just one of the multiple similar errors when trying to run it.

**Comment by glenncampagna** [comment]
### Questions about running model for OR4_8120_7890 @rburghol 
  - With the run command you provided , `HSP_VERSION=hsp2;export HSP_VERSION;cbp run_land.csh hsp2_2022 OR4_8120_7890` , what directory should we be running the model from?
 - Also, is there a certain amount of time we should expect it to take? We tested from the home directory but some errors appeared so we terminated early:
```
2022-08-02 13:33:02.24   Processing started for file ./; saveall=True
2022-08-02 13:33:02.64   Simulation Start: 1984-01-01 00:00:00, Stop: 2021-01-01 00:00:00
2022-08-02 13:33:02.64      IMPLND I001 DELT(minutes): 60
2022-08-02 13:33:05.91         ATEMP
2022-08-02 13:33:07.37         SNOW
2022-08-02 13:33:09.96         IWATER
Traceback (most recent call last):
  File "/usr/local/bin/hsp2", line 11, in <module>
    load_entry_point('HSPsquared', 'console_scripts', 'hsp2')()
  File "/opt/model/HSPsquared/HSP2tools/HSP2_CLI.py", line 60, in main
    mando.main()
  File "/usr/local/lib/python3.8/dist-packages/mando/core.py", line 208, in __call__
    return self.execute(sys.argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/mando/core.py", line 204, in execute
    return command(*a)
  File "/opt/model/HSPsquared/HSP2tools/HSP2_CLI.py", line 26, in run
    hsp2main(io_manager, saveall=saveall, jupyterlab=jupyterlab)
  File "/opt/model/HSPsquared/HSP2/main.py", line 209, in main
    errors, errmessages = function(io_manager, siminfo, ui, ts)
  File "/opt/model/HSPsquared/HSP2/IWATER.py", line 69, in iwater
    errors = _iwater_(ui, ts)                       # run IWATER simulation code
  File "/home/rob/.local/lib/python3.8/site-packages/numba/typed/dictobject.py", line 738, in impl
KeyError
Closing remaining open files:afoA51019.h5...done
mv: preserving permissions for ‘/media/model/p532/out/land/h5/afo/hsp2_2022/afoA51019.h5’: Operation not supported
Exporting IMPLND afo
Rscript /opt/model/p53/p532c-sova/run/export/export_hsp_h5.R /media/model/p532/out/land/h5/afo/hsp2_2022/afoA51019.h5 /media/model/p532/out/land/hsp2_2022/iwater/afoA51019_pwater.csv /RESULTS/IMPLND_I001/IWATER/table
Error in H5Dopen(fid, data_source_table) : 
  HDF5. Dataset. Can't open object.
Execution halted
scenario: Undefined variable.
running cfo for segment A51019 land scenario hsp2_2022
'../../..//config/blank_wdm/land.wdm' -> 'cfoA51019.wdm'
A51019, cfo
1003 reading from wdm
1005 reading from wdm

 
```
 - We see that the model is trying to run our export R script but is having an error, maybe because of the _pwater export path and iwater data source table? afo is an impervious land use so it should have an iwater table..
 - Lastly, using the rhdf5 package we see that some h5 files from the river see have been successfully generated and contain a results group, others are generated but do not contain the results group which we learned means the model hasn't been run yet, and other h5 files seem completely empty. Does this mean the model maybe has only been partially run for this river seg?
 Note: h5 files located where we'd expect them to be from the model run led us to believe the model might've already been run all the way through:
```
/opt/model/p53/p532c-sova/output/hspf/land/out/for/hsp2_2022/forA51019.h5
/opt/model/p53/p532c-sova/output/hspf/land/out/cid/hsp2_2022/cidA51019.h5
/opt/model/p53/p532c-sova/output/hspf/land/out/hyo/hsp2_2022/hyoA51019.h5
/opt/model/p53/p532c-sova/output/hspf/land/out/rpd/hsp2_2022/rpdA51019.h5
/opt/model/p53/p532c-sova/output/hspf/land/out/hyw/hsp2_2022/hywA51019.h5
/opt/model/p53/p532c-sova/output/hspf/land/out/nex/hsp2_2022/nexA51019.h5
```
through

```
/opt/model/p53/p532c-sova/output/hspf/land/out/afo/hsp2_2022/afoB51023.h5
/opt/model/p53/p532c-sova/output/hspf/land/out/rex/hsp2_2022/rexB51023.h5
/opt/model/p53/p532c-sova/output/hspf/land/out/alf/hsp2_2022/alfB51023.h5
/opt/model/p53/p532c-sova/output/hspf/land/out/lwm/hsp2_2022/lwmB51023.h5
```
A51019 is the first land segment listed within the river seg, and B51023 is the last (15 total)
